canvas = document.getElementById("myCanvas"); 
ctx = canvas.getContext("2d");

ctx.beginPath(); 
ctx.strokeStyle = "blue";
ctx.lineWidth = 10; 
ctx.arc(200,200, 80, 0, 2*Math.PI); 
ctx.stroke(); 
ctx.beginPath(); 
ctx.strokeStyle = "gold";
ctx.lineWidth = 10; 
ctx.arc(300,300, 80, 0, 2*Math.PI); 
ctx.stroke(); 
ctx.beginPath(); 
ctx.strokeStyle = "black";
ctx.lineWidth = 10; 
ctx.arc(400,200, 80, 0, 2*Math.PI); 
ctx.stroke();
ctx.stroke(); 
ctx.beginPath(); 
ctx.strokeStyle = "green";
ctx.lineWidth = 10; 
ctx.arc(500,300, 80, 0, 2*Math.PI); 
ctx.stroke();  
ctx.stroke(); 
ctx.beginPath(); 
ctx.strokeStyle = "red";
ctx.lineWidth = 10; 
ctx.arc(600,200, 80, 0, 2*Math.PI); 
ctx.stroke(); 